export const BASE_URL_PROD = 'https://auth-app-virid-eight.vercel.app/'
export const BASE_URL_DEV = 'http://localhost:3000/'
export const BASE_API = 'api/users/'

export const REGISTER = 'register'
export const LOGIN = 'login'
export const VERIFY = 'verify'
export const LOGOUT = 'logout'
export const BLOCK = 'block'
export const UNBLOCK = 'unblock'
export const DELETE = 'delete'